# Generated by Django 4.0 on 2021-12-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_author_alter_article_slug_article_author'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
